name: Secret Scanning with TruffleHog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Run TruffleHog secret scanner
        run: |
          trufflehog --json https://github.com/${{ github.repository }} > trufflehog-output.json
          
      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-output.json
